package cmp2804.tse.server.storage.symptoms

val SYMPTOMS = listOf(
    "Abdominal bloating",
    "Abdominal cramps",
    "Abdominal distention",
    "Abdominal pain",
    "Abdominal tenderness",
    "Acid reflux",
    "Ankle pain",
    "Ankle swelling",
    "Anxiety",
    "Aphasia",
    "Arm pain",
    "Auditory hallucinations",
    "Back pain",
    "Balance issues",
    "Bad breath",
    "Baldness",
    "Belching",
    "Black stools",
    "Bladder control issues",
    "Bladder pain",
    "Bladder spasms",
    "Blisters",
    "Blood in urine",
    "Blood in stool",
    "Bloodshot eyes",
    "Blurred vision",
    "Body aches",
    "Body chills",
    "Body temperature fluctuations",
    "Bradycardia",
    "Brain fog",
    "Breathing difficulties",
    "Breast pain",
    "Breast tenderness",
    "Breast lumps",
    "Bruising easily",
    "Burning sensation",
    "Chest pain",
    "Chest tightness",
    "Chills",
    "Chronic fatigue",
    "Chronic pain",
    "Cold extremities",
    "Cold intolerance",
    "Cold sores",
    "Collapsing",
    "Colorectal bleeding",
    "Confusion",
    "Constipation",
    "Coordination issues",
    "Cough",
    "Cracked skin",
    "Cramping",
    "Cravings",
    "Cysts",
    "Dandruff",
    "Dark urine",
    "Deafness",
    "Dehydration",
    "Delusions",
    "Depression",
    "Desensitization",
    "Decreased libido",
    "Diarrhea",
    "Difficulty concentrating",
    "Difficulty swallowing",
    "Disorientation",
    "Discoloration",
    "Dizziness",
    "Double vision",
    "Drooling",
    "Dry mouth",
    "Dry skin",
    "Dysmenorrhea (painful periods)",
    "Dyspareunia (painful intercourse)",
    "Dyspnea (shortness of breath)",
    "Dysuria (painful urination)",
    "Earache",
    "Ear discharge",
    "Ear ringing (tinnitus)",
    "Edema (swelling)",
    "Elbow pain",
    "Elevated heart rate",
    "Enlarged lymph nodes",
    "Enlarged spleen",
    "Epileptic seizures",
    "Erectile dysfunction",
    "Eye floaters",
    "Eye irritation",
    "Eye redness",
    "Eye strain",
    "Eyelid twitching",
    "Facial flushing",
    "Facial swelling",
    "Fainting (syncope)",
    "Fatigue",
    "Fever",
    "Finger pain",
    "Finger swelling",
    "Flatulence",
    "Floaters in vision",
    "Fluid retention",
    "Foot pain",
    "Frequent urination",
    "Gassiness",
    "Hallucinations",
    "Hair loss",
    "Hand pain",
    "Hand stiffness",
    "Hand swelling",
    "Headaches",
    "Hearing loss",
    "Heart palpitations",
    "Heartburn",
    "Heavy breathing",
    "Heavy periods",
    "Hemorrhoids",
    "Hiccups",
    "High blood pressure",
    "Hip pain",
    "Hirsutism (excess hair)",
    "Hoarseness",
    "Hot flashes",
    "Hyperactivity",
    "Hyperpigmentation",
    "Impaired cognition",
    "Impaired coordination",
    "Impotence",
    "Increased appetite",
    "Increased sweating",
    "Increased thirst",
    "Indigestion",
    "Inflammation",
    "Inflexibility",
    "Ingrown nails",
    "Insomnia",
    "Itching",
    "Itchy scalp",
    "Jaw pain",
    "Joint pain",
    "Joint stiffness",
    "Joint swelling",
    "Knee pain",
    "Lack of concentration",
    "Lack of energy",
    "Lack of libido",
    "Lethargy",
    "Light sensitivity",
    "Light headedness",
    "Limping",
    "Loss of appetite",
    "Loss of balance",
    "Loss of bowel control",
    "Loss of coordination",
    "Loss of hearing",
    "Loss of motor skills",
    "Loss of muscle tone",
    "Loss of sense of smell",
    "Loss of sense of taste",
    "Low back pain",
    "Low blood pressure",
    "Low libido",
    "Low-grade fever",
    "Lower limb pain",
    "Lung congestion",
    "Lymph node swelling",
    "Memory loss",
    "Menstrual irregularities",
    "Metabolic changes",
    "Migraine",
    "Mood swings",
    "Mouth sores",
    "Muscle cramps",
    "Muscle pain",
    "Muscle spasms",
    "Muscle stiffness",
    "Muscle wasting",
    "Muscle weakness",
    "Nail changes",
    "Nail clubbing",
    "Nasal congestion",
    "Nasal discharge",
    "Neck pain",
    "Neck stiffness",
    "Nerve pain",
    "Nervousness",
    "Night sweats",
    "Nightmares",
    "Numbness",
    "Oliguria (reduced urination)",
    "Oral ulcers",
    "Orthostatic hypotension",
    "Painful intercourse",
    "Painful urination",
    "Pale skin",
    "Palpitations",
    "Panic attacks",
    "Paresthesia (tingling or numbness)",
    "Pelvic pain",
    "Penile discharge",
    "Persistent cough",
    "Photosensitivity",
    "Poor memory",
    "Poor motor skills",
    "Poor vision",
    "Post-nasal drip",
    "Postural instability",
    "Pressure in the chest",
    "Rapid breathing",
    "Rapid heart rate",
    "Rectal bleeding",
    "Redness of skin",
    "Restlessness",
    "Ringing in the ears (tinnitus)",
    "Rashes",
    "Seizures",
    "Sensory overload",
    "Sensory sensitivity",
    "Sexual dysfunction",
    "Shaking",
    "Shivers",
    "Shortness of breath",
    "Shoulder pain",
    "Sinus congestion",
    "Sinus headaches",
    "Sinus pressure",
    "Skin changes",
    "Skin discoloration",
    "Skin irritation",
    "Skin lesions",
    "Skin rash",
    "Sleep disturbances",
    "Slurred speech",
    "Snoring",
    "Sore throat",
    "Spinal pain",
    "Spinal stenosis",
    "Spinal tenderness",
    "Spleen enlargement",
    "Spontaneous bleeding",
    "Stiff neck",
    "Stomach pain",
    "Stool changes",
    "Strep throat",
    "Stress",
    "Sweating (excessive or diminished)",
    "Swelling",
    "Swollen glands",
    "Teeth grinding",
    "Teeth sensitivity",
    "Testicular lumps",
    "Thigh pain",
    "Thirstiness",
    "Throat tightness",
    "Tingling sensation",
    "Toothache",
    "Tremors",
    "Urethral discharge",
    "Urticaria (hives)",
    "Vaginal discharge",
    "Vaginal dryness",
    "Vaginal itching",
    "Vaginal spotting,
    "Vertigo",
    "Vision changes",
    "Voice changes",
    "Vomiting",
    "Weakness",
    "Weight fluctuations",
    "Wheezing",
    "Wrist pain",
)
