package cmp2804.tse.server.storage.symptoms

val SYMPTOMS = listOf(
    "Abdominal bloating",
    "Abdominal cramps",
    "Abdominal distention",
    "Abdominal pain",
    "Abdominal tenderness",
    "Acid reflux",
    "Agitation",
    "Alcohol intolerance",
    "Allergies",
    "Anemia",
    "Ankle pain",
    "Ankle swelling",
    "Anorexia",
    "Anxiety",
    "Aphasia",
    "Appetite loss",
    "Arm pain",
    "Arrhythmia",
    "Arterial stiffening",
    "Arthritis",
    "Asthma",
    "Atrial fibrillation",
    "Attention deficit",
    "Auditory hallucinations",
    "Autoimmune reactions",
    "Back pain",
    "Balance issues",
    "Bad breath",
    "Baldness",
    "Belching",
    "Black stools",
    "Bladder control issues",
    "Bladder pain",
    "Bladder spasms",
    "Bladder stones",
    "Blisters",
    "Blood in urine",
    "Blood in stool",
    "Bloodshot eyes",
    "Blurred vision",
    "Body aches",
    "Body chills",
    "Body temperature fluctuations",
    "Bowel incontinence",
    "Bradycardia",
    "Brain fog",
    "Breathing difficulties",
    "Breast pain",
    "Breast tenderness",
    "Breast lumps",
    "Broken bones",
    "Bruising easily",
    "Burning sensation",
    "Cardiac arrhythmias",
    "Carpal tunnel syndrome",
    "Catarrh",
    "Cataracts",
    "Chest pain",
    "Chest tightness",
    "Chills",
    "Chronic fatigue",
    "Chronic pain",
    "Claudication (limping due to artery issues)",
    "Clumsiness",
    "Cold extremities",
    "Cold intolerance",
    "Cold sores",
    "Collapsing",
    "Colorectal bleeding",
    "Confusion",
    "Constipation",
    "Coordination issues",
    "Cough",
    "Cracked skin",
    "Cramping",
    "Cravings",
    "Croup",
    "Cysts",
    "Dandruff",
    "Dark urine",
    "Deafness",
    "Dehydration",
    "Delirium",
    "Delusions",
    "Dementia symptoms",
    "Depression",
    "Desensitization",
    "Decreased libido",
    "Diarrhea",
    "Difficulty concentrating",
    "Difficulty swallowing",
    "Disorientation",
    "Dislocated joints",
    "Discoloration",
    "Dizziness",
    "Double vision",
    "Drooling",
    "Dry mouth",
    "Dry skin",
    "Dysmenorrhea (painful periods)",
    "Dyspareunia (painful intercourse)",
    "Dyspnea (shortness of breath)",
    "Dysuria (painful urination)",
    "Earache",
    "Ear discharge",
    "Ear infections",
    "Ear ringing (tinnitus)",
    "Edema (swelling)",
    "Elbow pain",
    "Elevated heart rate",
    "Enlarged lymph nodes",
    "Enlarged spleen",
    "Epileptic seizures",
    "Erectile dysfunction",
    "Eruptions",
    "Eye floaters",
    "Eye infections",
    "Eye irritation",
    "Eye redness",
    "Eye strain",
    "Eyelid twitching",
    "Facial flushing",
    "Facial swelling",
    "Fainting (syncope)",
    "Fatigue",
    "Fever",
    "Fibromyalgia-like symptoms",
    "Finger pain",
    "Finger swelling",
    "Flatulence",
    "Flashes of light",
    "Floaters in vision",
    "Flu-like symptoms",
    "Fluid retention",
    "Foot pain",
    "Frequent urination",
    "Frustration",
    "Gas",
    "Gassiness",
    "Genital symptoms",
    "Gingivitis",
    "Gout",
    "Hallucinations",
    "Hair loss",
    "Hand pain",
    "Hand stiffness",
    "Hand swelling",
    "Hay fever",
    "Headaches",
    "Hearing loss",
    "Heart palpitations",
    "Heartburn",
    "Heavy breathing",
    "Heavy periods",
    "Hemorrhoids",
    "Hepatomegaly (enlarged liver)",
    "Hiccups",
    "Hip pain",
    "Hirsutism (excess hair)",
    "Hoarseness",
    "Hot flashes",
    "Hyperactivity",
    "Hyperpigmentation",
    "Hyperthermia",
    "Hypertension (high blood pressure)",
    "Hypothermia",
    "Hypotension (low blood pressure)",
    "Hypoxia",
    "Impaired cognition",
    "Impaired coordination",
    "Impotence",
    "Increased appetite",
    "Increased sweating",
    "Increased thirst",
    "Indigestion",
    "Inflammation",
    "Inflexibility",
    "Ingrown nails",
    "Insomnia",
    "Itching",
    "Itchy scalp",
    "Jaw pain",
    "Joint pain",
    "Joint stiffness",
    "Joint swelling",
    "Knee pain",
    "Lack of concentration",
    "Lack of energy",
    "Lack of libido",
    "Lethargy",
    "Light sensitivity",
    "Lightheadedness",
    "Limping",
    "Loss of appetite",
    "Loss of balance",
    "Loss of bowel control",
    "Loss of coordination",
    "Loss of hearing",
    "Loss of memory",
    "Loss of motor skills",
    "Loss of muscle tone",
    "Loss of sense of smell",
    "Loss of sense of taste",
    "Low back pain",
    "Low blood pressure",
    "Low libido",
    "Low-grade fever",
    "Lower limb pain",
    "Lung congestion",
    "Lymphedema",
    "Lymph node swelling",
    "Malaise",
    "Memory loss",
    "Menstrual irregularities",
    "Metabolic changes",
    "Migraine",
    "Mood swings",
    "Mouth sores",
    "Muscle atrophy",
    "Muscle cramps",
    "Muscle pain",
    "Muscle spasms",
    "Muscle stiffness",
    "Muscle wasting",
    "Muscle weakness",
    "Nail changes",
    "Nail clubbing",
    "Nasal congestion",
    "Nasal discharge",
    "Neck pain",
    "Neck stiffness",
    "Nerve pain",
    "Nervousness",
    "Night sweats",
    "Nightmares",
    "Numbness",
    "Oliguria (reduced urination)",
    "Oral ulcers",
    "Orthostatic hypotension",
    "Osteoporosis",
    "Painful intercourse",
    "Painful urination",
    "Pale skin",
    "Palpitations",
    "Panic attacks",
    "Paresthesia (tingling or numbness)",
    "Pelvic pain",
    "Penile discharge",
    "Peripheral neuropathy",
    "Persistent cough",
    "Photosensitivity",
    "Poor memory",
    "Poor motor skills",
    "Poor vision",
    "Post-nasal drip",
    "Postural instability",
    "Pressure in the chest",
    "Pseudocyesis (false pregnancy)",
    "Psoriasis",
    "Rapid breathing",
    "Rapid heart rate",
    "Rectal bleeding",
    "Redness of skin",
    "Restlessness",
    "Retinopathy",
    "Retinal detachment",
    "Ringing in the ears (tinnitus)",
    "Rashes",
    "Rheumatoid arthritis symptoms",
    "Sciatica",
    "Seizures",
    "Sensory overload",
    "Sensory sensitivity",
    "Sexual dysfunction",
    "Shaking",
    "Shivers",
    "Shortness of breath",
    "Shoulder pain",
    "Sinus congestion",
    "Sinus headaches",
    "Sinus pressure",
    "Skin changes",
    "Skin discoloration",
    "Skin irritation",
    "Skin lesions",
    "Skin rash",
    "Sleep apnea",
    "Sleep disturbances",
    "Slurred speech",
    "Snoring",
    "Sore throat",
    "Spinal pain",
    "Spinal stenosis",
    "Spinal tenderness",
    "Spleen enlargement",
    "Spontaneous bleeding",
    "Stiff neck",
    "Stomach pain",
    "Stool changes",
    "Strep throat",
    "Stress",
    "Stroke-like symptoms",
    "Sweating (excessive or diminished)",
    "Swelling",
    "Swollen glands",
    "Syncope (fainting)",
    "Tearing",
    "Teeth grinding",
    "Teeth sensitivity",
    "Testicular lumps",
    "Thigh pain",
    "Thirstiness",
    "Throat tightness",
    "Tingling sensation",
    "Toothache",
    "Torticollis",
    "Tremors",
    "Urethral discharge",
    "Urinary frequency",
    "Urinary incontinence",
    "Urinary tract infections",
    "Urticaria (hives)",
    "Vaginal discharge",
    "Vaginal dryness",
    "Vaginal itching",
    "Vaginal spotting",
    "Varicose veins",
    "Vertigo",
    "Vision changes",
    "Voice changes",
    "Vomiting",
    "Weakness",
    "Weight fluctuations",
    "Wheezing",
    "Wrist pain",
)