package cmp2804.tse.server.storage.symptoms

val SYMPTOMS = listOf(
    "Abnormal bleeding",
    "Abdominal bloating",
    "Abdominal cramps",
    "Abdominal distention",
    "Abdominal pain",
    "Abdominal tenderness",
    "Abnormal vaginal bleeding",
    "Abscesses",
    "Acid reflux",
    "Ankle pain",
    "Ankle swelling",
    "Anxiety",
    "Aphasia",
    "Arm pain",
    "Arrhythmia",
    "Asthma attacks",
    "Auditory hallucinations",
    "Back pain",
    "Balance issues",
    "Bad breath",
    "Baldness",
    "Belching",
    "Black stools",
    "Bladder control issues",
    "Bladder pain",
    "Bladder spasms",
    "Blisters",
    "Bloating",
    "Blood in urine",
    "Blood in stool",
    "Blood in vomit",
    "Bloodshot eyes",
    "Blurred vision",
    "Body aches",
    "Body chills",
    "Body temperature fluctuations",
    "Bradycardia",
    "Brain fog",
    "Breathing difficulties",
    "Breast pain",
    "Breast tenderness",
    "Breast lumps",
    "Bruising easily",
    "Bulging eyes",
    "Burning sensation",
    "Changes in bladder function",
    "Changes in eye apperance",
    "Changes in joint shape",
    "Changes in urine colour",
    "Changes in urine odour",
    "Changes in vision",
    "Changes of finger colour",
    "Changes of toe colour",
    "Chest pain",
    "Chest tightness",
    "Chills",
    "Cloudy urine",
    "Chronic fatigue",
    "Chronic pain",
    "Cold extremities",
    "Cold intolerance",
    "Cold sores",
    "Collapsing",
    "Colorectal bleeding",
    "Confusion",
    "Constipation",
    "Coordination issues",
    "Cough",
    "Coughing up blood",
    "Cracked skin",
    "Cramping",
    "Cravings",
    "Cysts",
    "Dandruff",
    "Dark urine",
    "Darkening skin",
    "Deafness",
    "Dehydration",
    "Delayed wound healing",
    "Delusions",
    "Depression",
    "Desensitization",
    "Decreased libido",
    "Diarrhea",
    "Difficulty concentrating",
    "Difficulty passing urine",
    "Difficulty sleeping",
    "Difficulty swallowing",
    "Difficulty weight bearing",
    "Disorientation",
    "Discoloration",
    "Dizziness",
    "Double vision",
    "Drooling",
    "Drooping eyelids",
    "Dry mouth",
    "Dry skin",
    "Dysmenorrhea (painful periods)",
    "Dyspareunia (painful intercourse)",
    "Dyspnea (shortness of breath)",
    "Dysuria (painful urination)",
    "Earache",
    "Ear discharge",
    "Ear ringing (tinnitus)",
    "Easy bruising",
    "Edema (swelling)",
    "Elbow pain",
    "Elevated heart rate",
    "Enlarged lymph nodes",
    "Enlarged spleen",
    "Epileptic seizures",
    "Erectile dysfunction",
    "Eye floaters",
    "Eye inflammtion",
    "Eye irritation",
    "Eye pain",
    "Eye redness",
    "Eye strain",
    "Eyelid twitching",
    "Exaustion",
    "Facial flushing",
    "Facial swelling",
    "Fainting (syncope)",
    "Fatigue",
    "Fever",
    "Finger pain",
    "Finger swelling",
    "Flatulence",
    "Floaters in vision",
    "Fluid retention",
    "Foot pain",
    "Frequent infections",
    "Frequent urination",
    "Gassiness",
    "Gential Burning",
    "Genital Discharge",
    "Genital itching",
    "Genital ulcers",
    "Hallucinations",
    "Hair loss",
    "Hand pain",
    "Hand stiffness",
    "Hand swelling",
    "Headaches",
    "Hearing loss",
    "Heart palpitations",
    "Heartburn",
    "Heavy breathing",
    "Heavy periods",
    "Hemorrhoids",
    "Hiccups",
    "High blood pressure",
    "Hip pain",
    "Hirsutism (excess hair)",
    "Hoarseness",
    "Hot flashes",
    "Hyperactivity",
    "Hyperpigmentation",
    "Impaired cognition",
    "Impaired coordination",
    "Impotence",
    "Increased appetite",
    "Increased sweating",
    "Increased thirst",
    "Indigestion",
    "Inflammation",
    "Inflexibility",
    "Ingrown nails",
    "Insomnia",
    "Itching",
    "Itchy scalp",
    "Jaundice",
    "Jaw pain",
    "Joint pain",
    "Joint stiffness",
    "Joint swelling",
    "Knee pain",
    "Lack of concentration",
    "Lack of energy",
    "Lack of libido",
    "Lethargy",
    "Light sensitivity",
    "Light headedness",
    "Lightening skin",
    "Limping",
    "Loss of appetite",
    "Loss of balance",
    "Loss of bowel control",
    "Loss of coordination",
    "Loss of hearing",
    "Loss of motor skills",
    "Loss of muscle tone",
    "Loss of sense of smell",
    "Loss of sense of taste",
    "Loss of vision",
    "Loud snoring",
    "Low back pain",
    "Low blood pressure",
    "Low libido",
    "Low-grade fever",
    "Lower limb pain",
    "Lung congestion",
    "Lymph node swelling",
    "Memory loss",
    "Menstrual irregularities",
    "Metabolic changes",
    "Migraine",
    "Missed periods",
    "Mood swings",
    "Mood changes",
    "Morning stiffness",
    "Mouth sores",
    "Muscle cramps",
    "Muscle pain",
    "Muscle spasms",
    "Muscle stiffness",
    "Muscle wasting",
    "Muscle weakness",
    "Nail changes",
    "Nail clubbing",
    "Nasal congestion",
    "Nasal discharge",
    "Nausea",
    "Neck pain",
    "Neck stiffness",
    "Nerve pain",
    "Nervousness",
    "Night sweats",
    "Nightmares",
    "Noisy breathing",
    "Numbness",
    "Oliguria (reduced urination)",
    "Oral ulcers",
    "Orthostatic hypotension",
    "Painful intercourse",
    "Painful menstruation",
    "Painful urination",
    "Pale skin",
    "Pale stools",
    "Palpitations",
    "Panic attacks",
    "Paresthesia (tingling or numbness)",
    "Pelvic pain",
    "Penile discharge",
    "Persistent cough",
    "Photosensitivity",
    "Poor memory",
    "Poor motor skills",
    "Poor vision",
    "Post-nasal drip",
    "Postural instability",
    "Pressure in the chest",
    "Rapid breathing",
    "Rapid heart rate",
    "Rectal bleeding",
    "Redness of skin",
    "Reduced mobility",
    "Restlessness",
    "Retching",
    "Ringing in the ears (tinnitus)",
    "Rashes",
    "Seizures",
    "Sensitvity to light",
    "Sensitivity to sunlgiht",
    "Sensory overload",
    "Sensory sensitivity",
    "Severe pain",
    "Sexual dysfunction",
    "Shaking",
    "Shivers",
    "Shortness of breath",
    "Shoulder pain",
    "Sinus congestion",
    "Sinus headaches",
    "Sinus pressure",
    "Skin changes",
    "Skin discoloration",
    "Skin irritation",
    "Skin lesions",
    "Skin rash",
    "Sleep disturbances",
    "Slurred speech",
    "Sneezing",
    "Snoring",
    "Sore throat",
    "Spinal pain",
    "Spinal stenosis",
    "Spinal tenderness",
    "Spleen enlargement",
    "Spontaneous bleeding",
    "Stiff neck",
    "Stomach pain",
    "Stool changes",
    "Strep throat",
    "Stress",
    "Sweating (excessive or diminished)",
    "Swelling",
    "Swelling in the legs",
    "Swollen glands",
    "Suicidal",
    "Teeth grinding",
    "Teeth sensitivity",
    "Testicular lumps",
    "Testicular pain",
    "Thigh pain",
    "Thirstiness",
    "Throat tightness",
    "Tingling sensation",
    "Toothache",
    "Tremors",
    "Urethral discharge",
    "Urticaria (hives)",
    "Urine leakage",
    "Vaginal discharge",
    "Vaginal dryness",
    "Vaginal itching",
    "Vaginal spotting",
    "Vertigo",
    "Vision changes",
    "Voice changes",
    "Vomiting",
    "Watery eyes",
    "Warts",
    "Weakness",
    "Weight fluctuations",
    "Weight gain",
    "Weight loss",
    "Wheezing",
    "Wrist pain",
)
